### ISSUE TITLE
Thread OP image is loaded using preview_reply instead of preview_op

### ISSUE THREAD

**Issue by miyachan** [bibanon/ayase#12]
While using the UI I noticed that the thread OP was really bad quality:

<img width="1467" alt="Screen Shot 2020-08-29 at 3 44 41 PM" src="https://user-images.githubusercontent.com/5410198/91647335-90eb4180-ea0e-11ea-9ad8-af17659929ef.png">

here's how it looks on 4chan:

<img width="1122" alt="Screen Shot 2020-08-29 at 3 55 49 PM" src="https://user-images.githubusercontent.com/5410198/91647486-1de2ca80-ea10-11ea-8dd0-f42cecc8d49b.png">

The problem is this image was previously uploaded as a reply and therefore has a lower quality image - you can see this in the database table:

```
mysql> SELECT * FROM a_images WHERE media_hash='ePUdQC9jcClfxUnjl6zMMQ==';
+----------+--------------------------+-------------------+--------------------+--------------------+-------+--------+
| media_id | media_hash               | media             | preview_op         | preview_reply      | total | banned |
+----------+--------------------------+-------------------+--------------------+--------------------+-------+--------+
|     6898 | ePUdQC9jcClfxUnjl6zMMQ== | 1598604502774.jpg | 1598718237609s.jpg | 1598604502774s.jpg |     2 |      0 |
+----------+--------------------------+-------------------+--------------------+--------------------+-------+--------+
1 row in set (0.04 sec)
``` 

Ayase is loading `preview_reply` for the OP image instead of `preview_op`. This is verified by looking at the URL Ayase is loading - it's loading `1598718237609s.jpg` instead of `1598604502774.jpg`. It should prefer the `preview_op` for OP posts.

**Comment by Amersel** [comment]
Should be fixed in 8a279cfd9ba908f7a02eb8d5b176e35e8268d3e6. 

Huh. I didn't know about the existence of preview_op. The code before this commit generated the preview based only on preview_reply or uses the timestamp from the media column to guess at the right image. This only mattered in the case that the media already existed in the table but not in an OP post.
